adios_iotest/settings: avoid an off-by-one
ornladios/ADIOS2 pull request #2654
Opened 2021-03-23 16:07 UTC by mathstuf

`argCopy`'s allocation did not save space for the `NUL` terminating
byte. Instead of manually calculating memory sizes, use `strdup`.

2021-05-25 14:49 UTC, chuckatkins commented
@mathstuf can you please address the msvc failure?

2021-05-25 15:19 UTC, mathstuf commented
The logs seem to have expired. Is there a way to rerun just the failed bits?

2021-05-25 15:21 UTC, mathstuf commented
I can try and rebase I guess; `master` looks OK.

2021-05-26 20:42 UTC, chuckatkins requested changes

2021-05-26 20:42 UTC, chuckatkins commented on source/utils/adios_iotest/settings.cpp
> +#ifdef _MSC_VER
should be `#ifdef _WIN32` as it's a windows issue, not an msvc issue.

2021-05-26 20:55 UTC, chuckatkins approved these changes

2021-05-26 22:42 UTC, merged