Fig bug in the IME file transport
ornladios/ADIOS2 pull request #3451
Opened 2023-01-30 17:43 UTC by anagainaru

This bug was introduced in PR #3388 
here:
[https://github.com/ornladios/ADIOS2/commit/f31d2cb05ff4dd375d431d8043d2e16aee798b64](https://github.com/ornladios/ADIOS2/commit/f31d2cb05ff4dd375d431d8043d2e16aee798b64#diff-4cb33e244ce899f10daacb5669a29eed59c1227475c9825e81ae68990a8de984)

I do not understand how the CI did not catch this nor did any of my previous runs. 

@pnorbert please make sure my fix is correct. Should we include checking this in the CI?

2023-01-30 21:10 UTC, pnorbert requested changes
Can I suggest to use a helper function for this entire code snippet? See FileAWSSDK.cpp
```
helper::SetParameterValue("synctopfs", params, m_SyncToPFS);
```

2023-01-30 21:53 UTC, anagainaru commented
> ```
> helper::SetParameterValue("synctopfs", params, m_SyncToPFS);
> ```

`syncToPFS` is a bool, the `SetParameterValue` expects a std::string as the last parameter, so in order to use the helper function I need to convert the string to a bool.

2023-01-30 22:09 UTC, pnorbert reviewed
Sorry, I missed that it was a string. This made it more complicated than your original fix. Also, the default value (true) is lost here in case the parameter is not set by the user. Please revert back to your original fix,

2023-01-31 02:18 UTC, anagainaru commented
@pnorbert done, mark your change as resolved and I'll merge this

2023-01-31 02:21 UTC, pnorbert approved these changes

2023-01-31 02:27 UTC, merged