Build scripts for ADIOS2 with CUDA and Kokkos backend
ornladios/ADIOS2 pull request #3579
Opened 2023-04-07 15:09 UTC by anagainaru

For Summit, Perlmutter and Crusher

2023-04-07 15:10 UTC, anagainaru commented
I am not sure we need 5 scripts, a lot of the things are the same but I didn't know where to document how to build Kokkos and what modules to use for each system.

2023-04-07 16:24 UTC, vicentebolea requested changes
@anagainaru they look great! I am in favor of having those as a help to deploy in those systems.

We normally pass the `shellcheck` script on shell scripts. Can you pass it and fix the potential warnings?

2023-04-07 16:24 UTC, vicentebolea commented on scripts/build_scripts/build-adios2-cuda-perlmutter.sh
> +BUILD_DIR=${ADIOS2_HOME}/build-cuda-summit
summit -> perlmutter

2023-04-07 16:27 UTC, vicentebolea commented
> I am not sure we need 5 scripts, a lot of the things are the same but I didn't know where to document how to build Kokkos and what modules to use for each system.

Maybe it is just ok for now, if we use those scripts more we can improve them iteratively

2023-04-07 17:29 UTC, pnorbert requested changes

2023-04-07 17:29 UTC, pnorbert commented on scripts/build_scripts/build-adios2-kokkos-perlmutter.sh
> +BUILD_DIR=${ADIOS2_HOME}/build-kokkos-summit
Same here, summit/perlmutter

2023-04-07 18:33 UTC, anagainaru commented
I did not know about `shellcheck`, that's so cool. Will fix all the warnings and the build names

2023-04-07 19:18 UTC, anagainaru commented
I fixed the warnings and the naming, I testing the new versions on Summit just to make sure I did not introduce some issues and it seems good.

2023-04-07 19:35 UTC, pnorbert submitted a review, later dismissed

2023-04-08 00:29 UTC, vicentebolea commented
@anagainaru can you do a amend and repush, it seems that the CI did not start. Lets try our new shellcheck test :)

2023-04-08 03:29 UTC, anagainaru commented
@vicentebolea I tried shellcheck online and I did not get this warnings.
I am not sure I understand what I am supposed to do for most of them. What is this one saying?
```
In scripts/build_scripts/build-adios2-cuda-perlmutter.sh line 21:
    -D CMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
       ^-------------------^ SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.
```

2023-04-08 18:04 UTC, vicentebolea commented
>  I am not sure I understand what I am supposed to do for most of them. What is this one saying?

I think that shellcheck is all confused about -D KEY=VALUE type of argument, you can either do like "-DKEY=VALUE" disable that specify check in that file. by adding `# shellcheck disable=SC2191`

2023-04-08 21:40 UTC, vicentebolea approved these changes

2023-04-08 23:23 UTC, merged