Enable shell check scripts for existing scripts
ornladios/ADIOS2 pull request #3940
Opened 2023-11-23 17:40 UTC by spyridon97

Enable shell check scripts for existing scripts

2023-11-23 18:03 UTC, vicentebolea commented
@spyridon97 thanks for the this change. We have to be very careful with these changes since we do not test all those files in CI, that it is why we have this "exclude" list. Everything which is not cover in CI should not be modified (Unless you run those scripts and verify that they work). 

Please remove changes for `scripts/runconf` `scripts/docker` `scripts/developer/` `scripts/ci/scripts/`

2023-11-23 18:04 UTC, vicentebolea commented on scripts/ci/gh-actions/macos-setup.sh
> +if [ ! -d /Applications/Xcode_"${XCODE_VER}".app ]
```suggestion
if [ ! -d "/Applications/Xcode_${XCODE_VER}.app" ]
```

2023-11-23 18:04 UTC, vicentebolea commented on scripts/ci/gh-actions/macos-setup.sh
> +sudo xcode-select --switch /Applications/Xcode_"${XCODE_VER}".app
same

2023-11-23 18:05 UTC, vicentebolea commented on scripts/ci/gh-actions/run.sh
> +if [ -f gha/scripts/ci/setup-run/ci-"${GH_YML_JOBNAME}".sh ]
same with the quotes in this file

2023-12-01 19:28 UTC, spyridon97 commented
@vicentebolea i see a weird ascent kokkos failure, shall i ignore this? If yes, can you approve?

2023-12-01 20:36 UTC, vicentebolea requested changes

2023-12-01 20:36 UTC, vicentebolea commented on scripts/ci/circle/run.sh
> +  if [ "$exit_status" -eq 0 ];
```suggestion
  if [ "$exit_status" -eq 0 ]
```

conditionals in bash does not need a semicolon if the `then` is in the next line

Apply this change in for the below cases too

2023-12-01 20:55 UTC, vicentebolea commented
> @vicentebolea i see a weird ascent kokkos failure, shall i ignore this? If yes, can you approve?

Yeah, the ascent build is flaky, you can ignore it

2023-12-04 16:55 UTC, spyridon97 commented
@vicentebolea can you approve now?

2023-12-04 17:37 UTC, vicentebolea approved these changes

2023-12-04 18:52 UTC, merged